// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_ANDROID_API_KEY',
    appId: '1:1065830735486:android:b41ed0afcfa530e90b822f',
    messagingSenderId: '1065830735486',
    projectId: 'gp-fir',
    storageBucket: 'gp-fir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FIREBASE_IOS_API_KEY',
    appId: '1:1065830735486:ios:186be172e32a718f0b822f',
    messagingSenderId: '1065830735486',
    projectId: 'gp-fir',
    storageBucket: 'gp-fir.firebasestorage.app',
    androidClientId: '1065830735486-e1958m6uhh2n2g72r77e4gfhh7o5ga30.apps.googleusercontent.com',
    iosClientId: '1065830735486-ia8i6bbkh4nmg0c2kmp3ibh82vro81in.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FIREBASE_WEB_API_KEY',
    appId: '1:1065830735486:web:6489e93cb8036d770b822f',
    messagingSenderId: '1065830735486',
    projectId: 'gp-fir',
    authDomain: 'gp-fir.firebaseapp.com',
    storageBucket: 'gp-fir.firebasestorage.app',
  );

}