// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEoF3UY64_sbfE2FB0yJZEu8FBOAsEZC0',
    appId: '1:333921750379:web:cf47eebb34434d511a102e',
    messagingSenderId: '333921750379',
    projectId: 'gpt1-d3b0d',
    authDomain: 'gpt1-d3b0d.firebaseapp.com',
    storageBucket: 'gpt1-d3b0d.firebasestorage.app',
    measurementId: 'G-847LLQWWV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAChJZ1Hs1Tt14kAqxlTiJQjL2dyl6BX6A',
    appId: '1:333921750379:android:dffbc9bcabf5e1831a102e',
    messagingSenderId: '333921750379',
    projectId: 'gpt1-d3b0d',
    storageBucket: 'gpt1-d3b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0wBMC9lQhWh-VP2PD7KoKTXnDppN8bbc',
    appId: '1:333921750379:ios:7dc977a5389985de1a102e',
    messagingSenderId: '333921750379',
    projectId: 'gpt1-d3b0d',
    storageBucket: 'gpt1-d3b0d.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );
}
