"""Add UserFoodLog table

Revision ID: 00645ab3f600
Revises: 
Create Date: 2026-04-26 17:18:03.246283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00645ab3f600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_food_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('serving_size', sa.Float(), nullable=True),
    sa.Column('log_time', sa.DateTime(), nullable=True),
    sa.Column('ai_scan', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birthdate',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birthdate',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    op.drop_table('user_food_logs')
    # ### end Alembic commands ###
