"""restore user goal weight and allergies

Revision ID: 04a5899626ad
Revises: 0d33dd01494e
Create Date: 2026-05-09 17:35:11.232762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a5899626ad'
down_revision = '0d33dd01494e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('allergies')
        batch_op.drop_column('goal_weight')

    # ### end Alembic commands ###
