"""extend food logs for meal type and scan id

Revision ID: 0d33dd01494e
Revises: 7ecb1eb3509f
Create Date: 2026-05-09 17:22:41.593145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d33dd01494e'
down_revision = '7ecb1eb3509f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_food_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('scan_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('food_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('serving_name', sa.String(length=100), nullable=True))
        batch_op.alter_column('food_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('goal_weight')
        batch_op.drop_column('allergies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergies', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('goal_weight', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('user_food_logs', schema=None) as batch_op:
        batch_op.alter_column('food_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('serving_name')
        batch_op.drop_column('food_item_id')
        batch_op.drop_column('scan_id')
        batch_op.drop_column('meal_type')

    # ### end Alembic commands ###
