"""add full report to user food logs

Revision ID: 426a53a26f55
Revises: 04a5899626ad
Create Date: 2026-05-09 17:58:40.726588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426a53a26f55'
down_revision = '04a5899626ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_food_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_report', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_food_logs', schema=None) as batch_op:
        batch_op.drop_column('full_report')

    # ### end Alembic commands ###
